#!/bin/bash

ENV=mac
ARCH=x64

ORIGINAL_PATH=$PATH
APP_HOME=$( cd "$( dirname "../${BASH_SOURCE[0]}" )" && pwd)
EXE_HOME=$APP_HOME/backend/bin/$ENV/$ARCH

echo $EXE_HOME

export ANGULAR_HOME=$APP_HOME
export NODE_HOME=$EXE_HOME/node
export NODE_EXE=$NODE_HOME/node

export MONGO_HOME=$EXE_HOME/mongo
export MONGOD_EXE=$MONGO_HOME/mongod

PATH=$DIR:$ANGULAR_HOME/node_modules/.bin:$MONGO_HOME:$NODE_HOME:$ANGULAR_HOME/backend/bin/$ENV/$ARCH/:$EXE_HOME/scripts/:$PATH

chmod u+x $EXE_HOME/scripts/* $ANGULAR_HOME/backend/httpServer/*.js
chmod u+x $ANGULAR_HOME/node_modules/protractor/selenium/*
chmod u+x $ANGULAR_HOME/node_modules/.bin/* $NODE_HOME/* $MONGO_HOME/*